### ISSUE TITLE
偶尔出现显示bug

### ISSUE THREAD

**Issue by sLin90** [yjy5264/react-native-card-carousel#1]
模拟器
![qq 20170104105454](https://cloud.githubusercontent.com/assets/5706753/21630459/3f072612-d26c-11e6-947b-230e1f27a1f8.png)

**Comment by GrootWanggg** [comment]
老哥，解决了吗？还是找了另外的库，这个库bug还挺多的。@289420843

**Comment by sLin90** [comment]
放弃这个库了

**Comment by yjy5264** [comment]
已经不写RN了，1年前写的不知道还能不能适配现在的版本，其实就是两个ScrollView重叠加点动画写的，可以自己试着写一下，并不难。
