### ISSUE TITLE
Make styles configurable through properties

### ISSUE THREAD

**Issue by gauravdhiman** [yjy5264/react-native-card-carousel#5]
Thanks for writing this nice component. One improvement - make the styles configurable through properties that get passed by parent component. I see right now the height, width, shadow etc are all hard-coded or determined within the component based on device height, width etc. It will be better if parent component can pass the required styles from outside and this component simply honor those.

For instance, I want cards to be of half a screen, but as right now its determined inside and its hard-coded as 250 px, I can not have a card of variable height.

**Comment by yjy5264** [comment]
now height is configurable
